services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - task-postgres-data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://taskuser:taskpass@db:5432/taskdb
    depends_on:
      - db

volumes:
  task-postgres-data:
    external: true
